In [1]:
import os
import pathlib
import tensorflow as tf
from model import BlazePose
from config import total_epoch, train_mode, best_pre_train, continue_train, batch_size, dataset

In [2]:
loss_func_mse = tf.keras.losses.MeanSquaredError()
loss_func_bce = tf.keras.losses.BinaryCrossentropy()

model = BlazePose().call()
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer, loss=[loss_func_bce, loss_func_mse, loss_func_bce])

In [3]:
model.summary()

Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 256, 256, 3) 0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 128, 128, 24) 672         input_1[0][0]                    
__________________________________________________________________________________________________
sequential (Sequential)         (None, 128, 128, 24) 840         conv2d[0][0]                     
__________________________________________________________________________________________________
tf_op_layer_AddV2 (TensorFlowOp [(None, 128, 128, 24 0           conv2d[0][0]                     
                                                                 sequential[0][0]      

In [4]:
pad_shape = tf.constant([[0, 0], [0, 0], [0, 0], [0, 24]])
pad_shape

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 0,  0],
       [ 0,  0],
       [ 0,  0],
       [ 0, 24]])>

In [8]:
paddings = tf.constant([[1, 1,], [2, 2]])
paddings

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 2]])>